simu:
  picFile: /p/project1/hai_1341/muralikrishnan1/Datasets_and_models_3D_electrostatic_plasma/GSP_2026/5_mini_apps_model_corrected_23_09_2026/3D_PIF_PIC_BH_5_mini_apps_unnormalized.h5
  nDim: 3

sample:
  iEnd: 601
  step: 1

data:
  dataClass: pic
  outType: solution
  outScaling: 1
  space_dim: 3
  xStep: 1
  yStep: 1
  zStep: 1
  seed: null
  dataFile: /p/project1/hai_1341/muralikrishnan1/Datasets_and_models_3D_electrostatic_plasma/GSP_2026/5_mini_apps_model_corrected_23_09_2026/PIF_PIC_BH_3D_5_mini_apps_QL_normalized.h5
  trainRatio: 0.8
  batchSize: 12        # Train Global Batch size
  val_batchSize: 1     # validation local Batch size 
  sampling_mode: None  # [fixed, ordered, random]
  gas: 1               # gradient accumulation steps
 

model:
  da: 3
  du: 3
  dv: 32
  kX: 16
  kY: 16
  kZ: 16
  n_dims: 3
  n_layers: 4
  bias: false
  non_linearity: gelu
  scaling_layers: 2
  use_postfnochannel_mlp: false
  channel_mlp_expansion: 4
  use_skip_connection: false
  skip_type: soft-gating
  use_dse: false                        # Direct Spectral Evaluation (DSE)
  matrix_free: true                    # DSE-matrix free
  use_kb: false                         # Kaiser-Bessel NUFFT
  use_toeplitz: false                   # Toeplitz NUFFT
  use_finufft: true                     # Pytorch-Finufft
  

optim:
  name: adam
  lr: 1.0e-3
  weight_decay: 1.0e-4

lr_scheduler:
  # scheduler: CosAnnealingLR
  # T_max: 50000
  scheduler: StepLR
  step_size: 50.0
  gamma: 0.5

loss:
  name: L1Loss
  # absolute: false
  
parallel_strategy:
  ddp: false        # Distributed Data Parallel
  tp : false       # Tensor Parallel(Only for PIC-DSE)
  tp_size: 1       # must be divisible by nParticle          
  gpus_per_node: 4

train:
  trainDir: /p/project1/hai_1341/muralikrishnan1/Datasets_and_models_3D_electrostatic_plasma/GSP_2026/5_mini_apps_model_corrected_23_09_2026/model
  epochs: 250                     # nEpochs
  checkpoint: /p/project1/hai_1341/muralikrishnan1/Datasets_and_models_3D_electrostatic_plasma/GSP_2026/5_mini_apps_model_corrected_23_09_2026/model/model_epoch300.pt  
  saveInterval: 50
  disableTensorboard: true
  measure_power: 0             # measure power and energy using jpwr

eval:
  runId: 1
  imgExt: png
  evalDir: /p/scratch/pepcexa/muralikrishnan1/operator_learning/scripts/pic_eval/3D_NUFFT
  dim: 3
  NG : 32
  Vt: 1
  nParticle: 100000
  Qm : -1
  ref: pif

testCases:
  weakLandau:
    T: 10
    dt: 0.05
    kc: 0.5
    alpha: 0.05
  
profile:
  enableProfiler: false
  profiler: nsys
  profileDir: nsysProf
  evalOnly: true
  input_shape: [1,3,10000]   # relevant only if evalOnly=true or compile_eval=true
  use_amp: 0
  use_complex_amp: 0
  benchmark: true
  niter: 5
  compile_eval: 0       
  compile_train: 0
  compile_mode: default    # compiler mode 
 
